// CONFIGURATION ---------- start
// scriptId (script number) is last number from address bar of 
// Shelly script editor e.g.: http://192.168.0.40/#/script/1
const scriptId = 7;
//number of pulses generated by the script
let pulsesNumber = 3;
// pulse length - time when relay is ON in ms
const relayOnTime = 500;
// pause length - time when relay is OFF in ms
const relayOffTime = 1000;
// CONFIGURATION ---------- end

let timerHandle = null; 
let fsaPtr = 1; // finite state automaton pointer

// ============================================================
// Function switches the relay ON and OFF in number of cycles 
// as defined by "pulsesNumber" variable.
// ON and OFF time of the relay is defined by the variables:
// "relayOnTime" and "relayOffTime"
function finiteStateAutomaton() {
  switch(fsaPtr) {
    case 1: // switch relay on
      fsaPtr = 2;
      Shelly.call("Switch.Set", "{id:0, on:true}");
      timerHandle = Timer.set(relayOnTime, false, finiteStateAutomaton);    
    break;
    
    case 2: // switch relay off and stop the script if all pulses have been realised
      Shelly.call("Switch.Set", "{ id:0, on:false}");
      pulsesNumber--;
      if (pulsesNumber === 0) {
        Timer.clear(timerHandle);
        Shelly.call("Script.Stop", {"id": scriptId});     
      } else {
        fsaPtr = 1;
        timerHandle = Timer.set(relayOffTime, false, finiteStateAutomaton);      
      };
    break;    
  };
};

// start Finite State Automaton function
finiteStateAutomaton();